services:
  server:
    build: .
    env_file:
      - .env
    environment:
      MONGO_HOST: mongodb
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8000:8000
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    env_file:
      - .env
    command: mongod --quiet --logpath /dev/null 
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 1s
      retries: 60

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379
